default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8

development:
  <<: *default
  database: home_next_development
  host: 127.0.0.1
  port: 3306
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>

test:
  <<: *default
  database: home_next_test
  host: 127.0.0.1
  port: 3306
  pool: 5
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
