default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: home_next_development
  host: 127.0.0.1
  port: 5432
  username: <%= ENV['POSTGRES_DB_ROLE'] %>

test:
  <<: *default
  database: home_next_test
  host: 127.0.0.1
  port: 5432
  username: <%= ENV['POSTGRES_DB_ROLE'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
