---
:verbose: false
:concurrency: 10
:timeout: 25

:queues:
  - critical
  - default
  - low

# you can override concurrency based on environment
production:
  :concurrency: 25
staging:
  :concurrency: 15
